"""Geometry layer: sketches and Part Design features on top of `core.Part`.

Exposes `Sketch`/`SketchCollection` (2D profiles on origin planes),
`SketchFeature`/`Pad`/`Pocket`/`RevolvedFeature`/`Shaft`/`Groove`/`Mirror`/
`Rib`/`Slot`/`RectangularPattern`/`ConstRadEdgeFillet`/`Chamfer`/`PartDesign`
(extruded, pocketed, revolved, mirrored, ribbed, slotted, patterned, filleted,
and chamfered solid features), `Edge`/`EdgeSnapshot` (the edge-reference layer
those last two features are built on), and `Constraint`/`ConstraintCollection`
(sketch constraints, created only through `SketchEditor` inside
`Sketch.edit()`), matching the verified COM surface documented in
`docs/conventions.md` sections 1.2/1.2.1/1.2.2/1.2.2.2/1.2.3/1.2.4/1.2.5/1.3
and the public API contract in sections 6.9/6.10/6.11/6.13/6.14/6.16/6.17.
"""

from auto_3dx.geometry.constraint import (
    CONSTRAINT_COINCIDENT,
    CONSTRAINT_CONCENTRICITY,
    CONSTRAINT_DISTANCE,
    CONSTRAINT_HORIZONTAL,
    CONSTRAINT_LENGTH,
    CONSTRAINT_PARALLEL,
    CONSTRAINT_PERPENDICULAR,
    CONSTRAINT_RADIUS,
    CONSTRAINT_TANGENT,
    CONSTRAINT_VERTICAL,
    Constraint,
    ConstraintCollection,
)
from auto_3dx.geometry.edges import EDGE_SEARCH_QUERY, Edge, EdgeSnapshot
from auto_3dx.geometry.part_design import (
    CHAMFER_KIND,
    CHAMFER_MODE_VERIFIED,
    CHAMFER_ORIENTATION_0,
    CHAMFER_ORIENTATION_1,
    CHAMFER_PROPAGATION_0,
    CHAMFER_PROPAGATION_1,
    EDGE_FILLET_KIND,
    EDGE_FILLET_PROPAGATION_VERIFIED,
    FULL_REVOLUTION,
    GROOVE_KIND,
    LENGTH_TOLERANCE,
    MIRROR_KIND,
    PAD_KIND,
    PATTERN_DIRECTION_NEGATIVE_X,
    PATTERN_DIRECTION_NEGATIVE_Y,
    PATTERN_DIRECTION_NEGATIVE_Z,
    PATTERN_DIRECTION_X,
    PATTERN_DIRECTION_Y,
    PATTERN_DIRECTION_Z,
    POCKET_KIND,
    RECTANGULAR_PATTERN_KIND,
    RIB_KIND,
    SHAFT_KIND,
    SLOT_KIND,
    SUPPORTED_CHAMFER_ORIENTATIONS,
    SUPPORTED_CHAMFER_PROPAGATIONS,
    SUPPORTED_EDGE_FILLET_PROPAGATIONS,
    SUPPORTED_PATTERN_DIRECTIONS,
    Chamfer,
    ConstRadEdgeFillet,
    Groove,
    Mirror,
    Pad,
    PartDesign,
    Pocket,
    RectangularPattern,
    RevolvedFeature,
    Rib,
    Shaft,
    SketchFeature,
    Slot,
)
from auto_3dx.geometry.sketch import (
    AXIS_TOLERANCE,
    SUPPORT_XY,
    SUPPORT_YZ,
    SUPPORT_ZX,
    SUPPORTED_SKETCH_SUPPORTS,
    Sketch,
    SketchCollection,
    SketchEditor,
)

__all__ = [
    "AXIS_TOLERANCE",
    "SUPPORT_XY",
    "SUPPORT_YZ",
    "SUPPORT_ZX",
    "SUPPORTED_SKETCH_SUPPORTS",
    "Sketch",
    "SketchCollection",
    "SketchEditor",
    "LENGTH_TOLERANCE",
    "PAD_KIND",
    "POCKET_KIND",
    "SHAFT_KIND",
    "GROOVE_KIND",
    "MIRROR_KIND",
    "RECTANGULAR_PATTERN_KIND",
    "RIB_KIND",
    "SLOT_KIND",
    "PATTERN_DIRECTION_X",
    "PATTERN_DIRECTION_Y",
    "PATTERN_DIRECTION_Z",
    "PATTERN_DIRECTION_NEGATIVE_X",
    "PATTERN_DIRECTION_NEGATIVE_Y",
    "PATTERN_DIRECTION_NEGATIVE_Z",
    "SUPPORTED_PATTERN_DIRECTIONS",
    "FULL_REVOLUTION",
    "SketchFeature",
    "Pad",
    "Pocket",
    "RevolvedFeature",
    "Shaft",
    "Groove",
    "Mirror",
    "Rib",
    "Slot",
    "RectangularPattern",
    "EDGE_SEARCH_QUERY",
    "Edge",
    "EdgeSnapshot",
    "EDGE_FILLET_KIND",
    "CHAMFER_KIND",
    "EDGE_FILLET_PROPAGATION_VERIFIED",
    "SUPPORTED_EDGE_FILLET_PROPAGATIONS",
    "CHAMFER_MODE_VERIFIED",
    "CHAMFER_PROPAGATION_0",
    "CHAMFER_PROPAGATION_1",
    "SUPPORTED_CHAMFER_PROPAGATIONS",
    "CHAMFER_ORIENTATION_0",
    "CHAMFER_ORIENTATION_1",
    "SUPPORTED_CHAMFER_ORIENTATIONS",
    "ConstRadEdgeFillet",
    "Chamfer",
    "PartDesign",
    "CONSTRAINT_HORIZONTAL",
    "CONSTRAINT_VERTICAL",
    "CONSTRAINT_LENGTH",
    "CONSTRAINT_RADIUS",
    "CONSTRAINT_PERPENDICULAR",
    "CONSTRAINT_PARALLEL",
    "CONSTRAINT_DISTANCE",
    "CONSTRAINT_COINCIDENT",
    "CONSTRAINT_CONCENTRICITY",
    "CONSTRAINT_TANGENT",
    "Constraint",
    "ConstraintCollection",
]
