"""Public API for automating a running 3DEXPERIENCE CATIA session."""

from auto_3dx.core.application import Catia, EditorInfo
from auto_3dx.core.part import Part
from auto_3dx.errors import (
    AmbiguousNameError,
    Auto3dxError,
    CatiaConnectionError,
    Com3dxNotFoundError,
    ConstraintNotFoundError,
    FeatureConflictError,
    FeatureNotFoundError,
    FormulaAlreadyExistsError,
    FormulaNotFoundError,
    NoActiveEditorError,
    NoActivePartError,
    ParameterAlreadyExistsError,
    ParameterNameError,
    ParameterNotFoundError,
    ParameterTypeError,
    PartialCreationError,
    PartUpdateError,
    SketchAlreadyExistsError,
    SketchNotFoundError,
    SketchSupportMismatchError,
    StaleSnapshotError,
    UnsupportedMagnitudeError,
    UnsupportedSupportError,
    UnsupportedUnitError,
)
from auto_3dx.formulas.collection import FormulaCollection
from auto_3dx.formulas.formula import Formula
from auto_3dx.geometry.constraint import Constraint, ConstraintCollection
from auto_3dx.geometry.edges import Edge, EdgeSnapshot
from auto_3dx.geometry.faces import Face, FaceSnapshot
from auto_3dx.geometry.part_design import (
    Chamfer,
    ConstRadEdgeFillet,
    Groove,
    Hole,
    Mirror,
    Pad,
    PartDesign,
    Pocket,
    RectangularPattern,
    RevolvedFeature,
    Rib,
    Shaft,
    Shell,
    SketchFeature,
    Slot,
    Thickness,
)
from auto_3dx.geometry.planes import AnglePlane, OffsetPlane, Plane, PlaneCollection
from auto_3dx.geometry.sketch import Sketch, SketchCollection, SketchEditor
from auto_3dx.measurement import (
    MassProperties,
    SolidMeasurement,
)
from auto_3dx.parameters.collection import ParameterCollection
from auto_3dx.parameters.parameter import Parameter, ParameterInfo
from auto_3dx.parameters.units import UnitCatalogue, UnitInfo

__all__ = [
    "Catia",
    "EditorInfo",
    "Part",
    "Parameter",
    "ParameterCollection",
    "ParameterInfo",
    "UnitCatalogue",
    "UnitInfo",
    "Constraint",
    "ConstraintCollection",
    "Formula",
    "FormulaCollection",
    "Groove",
    "Mirror",
    "Pad",
    "PartDesign",
    "Pocket",
    "RectangularPattern",
    "Edge",
    "EdgeSnapshot",
    "Face",
    "FaceSnapshot",
    "Chamfer",
    "ConstRadEdgeFillet",
    "Hole",
    "Shell",
    "Thickness",
    "Plane",
    "OffsetPlane",
    "AnglePlane",
    "PlaneCollection",
    "StaleSnapshotError",
    "RevolvedFeature",
    "Rib",
    "Shaft",
    "SketchFeature",
    "Slot",
    "Sketch",
    "SketchCollection",
    "SketchEditor",
    "MassProperties",
    "SolidMeasurement",
    "AmbiguousNameError",
    "Auto3dxError",
    "CatiaConnectionError",
    "Com3dxNotFoundError",
    "ConstraintNotFoundError",
    "FeatureConflictError",
    "FeatureNotFoundError",
    "FormulaAlreadyExistsError",
    "FormulaNotFoundError",
    "NoActiveEditorError",
    "NoActivePartError",
    "ParameterAlreadyExistsError",
    "ParameterNameError",
    "ParameterNotFoundError",
    "ParameterTypeError",
    "PartialCreationError",
    "PartUpdateError",
    "SketchAlreadyExistsError",
    "SketchNotFoundError",
    "SketchSupportMismatchError",
    "UnsupportedMagnitudeError",
    "UnsupportedSupportError",
    "UnsupportedUnitError",
]
