"""Public API for auto_3dx: attach to a running 3DEXPERIENCE session and edit Part parameters."""

from auto_3dx.core.application import Catia, EditorInfo
from auto_3dx.core.part import Part
from auto_3dx.errors import (
    AmbiguousNameError,
    Auto3dxError,
    CatiaConnectionError,
    Com3dxNotFoundError,
    ConstraintNotFoundError,
    FeatureConflictError,
    FeatureNotFoundError,
    FormulaAlreadyExistsError,
    FormulaNotFoundError,
    NoActiveEditorError,
    NoActivePartError,
    ParameterAlreadyExistsError,
    ParameterNameError,
    ParameterNotFoundError,
    ParameterTypeError,
    PartialCreationError,
    PartUpdateError,
    SketchAlreadyExistsError,
    SketchNotFoundError,
    SketchSupportMismatchError,
    UnsupportedSupportError,
    UnsupportedUnitError,
)
from auto_3dx.formulas.collection import FormulaCollection
from auto_3dx.formulas.formula import Formula
from auto_3dx.geometry.constraint import Constraint, ConstraintCollection
from auto_3dx.geometry.part_design import (
    Groove,
    Mirror,
    Pad,
    PartDesign,
    Pocket,
    RevolvedFeature,
    Shaft,
    SketchFeature,
)
from auto_3dx.geometry.sketch import Sketch, SketchCollection, SketchEditor
from auto_3dx.parameters.collection import ParameterCollection
from auto_3dx.parameters.parameter import Parameter, ParameterInfo

__all__ = [
    "Catia",
    "EditorInfo",
    "Part",
    "Parameter",
    "ParameterCollection",
    "ParameterInfo",
    "Constraint",
    "ConstraintCollection",
    "Formula",
    "FormulaCollection",
    "Groove",
    "Mirror",
    "Pad",
    "PartDesign",
    "Pocket",
    "RevolvedFeature",
    "Shaft",
    "SketchFeature",
    "Sketch",
    "SketchCollection",
    "SketchEditor",
    "AmbiguousNameError",
    "Auto3dxError",
    "CatiaConnectionError",
    "Com3dxNotFoundError",
    "ConstraintNotFoundError",
    "FeatureConflictError",
    "FeatureNotFoundError",
    "FormulaAlreadyExistsError",
    "FormulaNotFoundError",
    "NoActiveEditorError",
    "NoActivePartError",
    "ParameterAlreadyExistsError",
    "ParameterNameError",
    "ParameterNotFoundError",
    "ParameterTypeError",
    "PartialCreationError",
    "PartUpdateError",
    "SketchAlreadyExistsError",
    "SketchNotFoundError",
    "SketchSupportMismatchError",
    "UnsupportedSupportError",
    "UnsupportedUnitError",
]
